//import { buildAppProto } from "../js/appproto.js";
//import { erase } from "../js/main.js";

var c_connected = false;
var websocket  = null;
var xhttp;
// set boot partition 			- client2server
//								- response: refresh page
const SETBOOT           = "setBoot";

//upload partition image status	- server2client 
// generated by flashing_post_handler()
const USTATUS = "ustatus";

// dump partition image status	-server2client
// generated by dump_get_handler()
const DSTATUS 	        = "dstatus";	

/*
ERASE partition flow
client to server 	ERASE\1query\1\partition name\1
server to client 	ERASESTATUS\1error\error message\1
					ERASESTATUS\1confirm\1part name\1
client to server 	ERASE\1confirmok\1part name\1
server to client 	ERASESTATUS\1progress\1progress message\1
*/

// erase partition				- client2server
//								- response ERASESTATUS
const ERASE		        = "erase";
const ERASESTATUS	    = "erasestatus";

// create NVS key/value pair	- client2server
// responds with ESP_OK/ESP_FAIL
const CREATEKEY		    = "createkey";

/*
update key flow
1. client 2 server		UPD_REQUEST\1keyID\1length\1#chunks\1
2. server 2 client		SEND_VAL\1keyID
3. client 2 server		UPDATE_VAL\1keyID\1#chunk\1length\1
	for NVS_TYPE_STR or BLOB step3 repeats util entire key value is sent
4.server 2 client		UPDATE_KEY\1keyID\1keyName\1error code\1error string
*/
const UPD_REQUEST		= "update req";
const SEND_VAL		    = "send val";
const UPDATE_VAL		= "update val";
const UPDATE_KEY		= "update key";

/*
delete key flow
client 2 server			DELETE_NS\1namespaceName\1
						DELETE_KEY\1keyID\1
server 2 client			DELETE_KEY_RESP\1key|namespace name\1error code\1error string\1
*/
const DELETE_NS		    = "delete ns";
const DELETE_KEY		= "delete key";
const DELETE_KEY_RESP	= "delete key resp";

//server 2 client		DUMP_KEY\1keyID\1keyName\1error code\1error string\1
const DUMP_KEY		    = "dump key";

window.addEventListener("DOMContentLoaded", pageload);

function setBoot()
	{
	var pName = document.getElementById("parts").value;
	var msg = createMessage(CMD_SETBOOT, [pName], payload = null);
	var ws_string = buildAppProto(msg);
	ws_send(ws_string);
	}
function erase()
	{
	var pName = document.getElementById("parts").value;
	var msg = createMessage(CMD_ERASEPART, [pName], payload = null);
	var ws_string = buildAppProto(msg);
	ws_send(ws_string);
	}
function update(fName) 
	{
	if(fName == "reboot")
		{
		document.getElementById(fName).method = "POST";
		document.getElementById(fName)[0].value = "1";
		document.getElementById(fName).action = "/a";
		}
	}
function esp_reboot()
	{
	var msg = createMessage(CMD_REBOOT, [], payload = null);
	var ws_string = buildAppProto(msg);
	ws_send(ws_string);
	}
function ws_send(msg)
	{
	if(websocket.readyState == WebSocket.OPEN)
		websocket.send(msg);
	else
		alert("not connected to websocket server");
	}
function ws_receive(msg)
	{
	console.log('RECEIVED:', msg.data.slice(0, 40));
	const parsed = parseAppProto(msg.data);
	if(parsed.ret != 0)
		return;
	if(parsed.msg.command == CMD_REQCONF)
		{
		let c = confirm('Erasing ' + parsed.msg.params[1] + ' all data will be lost!\nPress "OK" to continue');
		if(c)
			{
			let msgOut = createMessage(RSP_CONFIRMATION, [parsed.msg.params[0], parsed.msg.params[1], "OK"], null);
			let buffer = buildAppProto(msgOut);
			ws_send(buffer);
			}
		}
	else if(parsed.msg.command == RSP_CMD)
		{
		if(parsed.msg.params[0] == CMD_SETBOOT)
			{
			if(parsed.msg.params[2] != "0") //error setting boot flag
				alert("Cannot set boot flag to " + parsed.msg.params[1] + "\n" + parsed.msg.params[3]);
			else
				window.location.reload(true);
			}
		else if(parsed.msg.params[0] == CMD_REBOOT)
			{
			window.location.reload(true);
			}
		}
	else if(parsed.msg.command == URC_STATUS)
		{
		if(parsed.msg.params[0] == OP_DOWNLOAD)
			{
			if(parsed.msg.params[1] == PAR_ERROR)
				alert("Download error: " + parsed.msg.params[2] + "\n" + parsed.msg.params[3]);
			}
		if(parsed.msg.params[0] == OP_UPLOAD)
			{
			if(parsed.msg.params[1] == PAR_PROGRESS)
				document.getElementById("ustatus").innerHTML = "flashing... " + parsed.msg.params[3] + "%";
			else if(parsed.msg.params[1] == PAR_ERROR)
				{
				alert("Flashing error: " + parsed.msg.params[2] + "\n" + parsed.msg.params[3]);
				document.getElementById("upload").disabled = false;
				}
			}
		}
	/*
	var params = msg.data.split('\x01');
	if(params[0] == "setBoot" && params.length == 3)
		{
		if(params[1] != "ESP_OK")
			alert("Cannot set boot flag to " + params[2] + "\n" + params[1]);
		}
	else if(params[0] == "refresh")
		{
		if(params.length == 3)
			loc = window.location.origin + "/?" + params[1] + "=" + params[2];
		else
			loc = window.location.origin;
		window.location = loc;
		}
	else if(params[0] == "ustatus")
		{
		if(params[1] == "progress")
			document.getElementById("ustatus").innerHTML = "flashing... " + params[2];
		else if(params[1] == "error")
			{
			//if(upload_inp == 1)
				xhttp.abort();
			}
		}
	else if(params[0] == "dstatus")
		{
		if(params[1] == "progress")
			alert(params[2]);
		}
	else if(params[0] == "erasestatus")
		{
		if(params[1] == "error")
			alert(params[2]);
		else if(params[1] == "confirm")
			{
			//var pName = document.getElementById("parts").value;
			if(confirm('Erasing ' + params[2] + ' all data will be lost!\nPress "OK" to continue') == true)
				ws_send("erase" + '\x01confirmok\x01' + params[2] + '\x01');
			}
		else if(params[1] == "progress")
			alert(params[2]);
		}
		*/
	}
function selFile(event)
	{
	document.getElementById("ustatus").innerHTML = "";
	}
function upload() 
	{
    var upload_path = "/upload/" + document.getElementById("parts").value; //filePath;
    var fileInput = document.getElementById("newfile").files;
	if(fileInput.length == 0)
		{
		alert("No file chosen!!!");
		return;
		}
    var file = fileInput[0];

	xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() 
		{
		if (xhttp.readyState == 4) 
			{
            if (xhttp.status == 200) 
				document.getElementById("ustatus").innerHTML = "Flashing complete";
			else 
                alert(xhttp.status + " Error!\n" + xhttp.responseText);
			document.getElementById("upload").disabled = false;
        	}
		};
	xhttp.onerror = function() {alert("Network error during upload");};
	xhttp.open("POST", upload_path, true);
	document.getElementById("upload").disabled = true;
    xhttp.send(file);   // ✅ send file directly
	}
function dump()
	{
	var name = document.getElementById("parts").value;
	window.location.href =
        "/download/" + encodeURIComponent(name);
	}
function pageload()
    {
    const wsUri = window.location.origin + "/ws";
	websocket = new WebSocket(wsUri);
	websocket.addEventListener("open", () => {console.log("CONNECTED"); c_connected = true;});
	websocket.addEventListener("close", (event) => {console.log("DISCONNECTED: " + event.data); c_connected = false;});
	websocket.onmessage = (msg) => {ws_receive(msg);};
	}